sportsequipment/app/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'app'

urlpatterns = [
    path('test' , views.common.test , name='test'),


    # 8个html页面
    path('' , views.homepage.home , name='home'), #添加映射
    path('index' , views.indexpage.index , name='index'),
    path('login', views.loginpage.login, name='login'),
    path('message', views.messagepage.message, name='message'),
    path('repair' , views.repairpage.repair , name='repair'),
    path('register', views.registerpage.register, name='register'),
    path('myrent', views.myrentpage.myrent, name='myrent'),
    path('setting', views.settingpage.setting, name='setting'),
    path('manage_borrow',views.managepage.borrow,name='manage_borrow'),
    path('manage_repair',views.managepage.repair,name='manage_repair'),





    path('do_login', views.loginpage.do_login, name='do_login'),
    path('logout', views.loginpage.logout, name='logout'),
    path('do_register', views.registerpage.do_register, name='do_register'),
    path('do_borrow', views.indexpage.do_borrow, name='do_borrow'),
    path('get_message', views.messagepage.get_message, name='get_message'),
    path('get_equipment', views.indexpage.get_equipment, name='get_equipment'),
    path('recive_equipment', views.myrentpage.recive_equipment, name='recive_equipment'),
    path('return_equipment', views.myrentpage.return_equipment, name='return_equipment'),
    path('delete_message', views.messagepage.get_message, name='delete_message'),
    path('read_message', views.messagepage.get_message, name='read_message'),
    path('submit_repair', views.repairpage.submit_repair, name='submit_repair'),

]

sportsequipment/sportsequipment/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.conf.urls import include
from django.urls import path, include, re_path
from django.views.static import serve
from sportsequipment.settings import MEDIA_ROOT

app_name = 'app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    # 处理图片显示的url,使用Django自带serve,传入参数告诉它去哪个路径找，我们有配置好的路径MEDIAROOT
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT }),
    # url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),
    # path('' , views.home , name='home'), #添加映射
]

sportsequipment/templates/old/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
  <p>测试</p>
</body>
</html>

sportsequipment/templates/old/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <!--            用百度的静态资源库的cdn安装bootstrap环境-->
<!--         Bootstrap 核心 CSS 文件-->
        <link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
        <!--font-awesome 核心我CSS 文件-->
        <link href="//cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <!-- 在bootstrap.min.js 之前引入 -->
        <script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>
        <!-- Bootstrap 核心 JavaScript 文件 -->
        <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>



        <link rel="stylesheet" href="{% static 'css/index.css' %}">



    </head>
    <body>
        <header>
            <nav class="b_clear">
                <div class="nav_logo l_float">
                    <img src="{% static 'img/neau_cut.png'%}" alt="">
                </div>
                <div class="nav_link r_float">
                    <ul>
                        <li><a href="#">返回首页</a></li>
                        <li><a href="#">关于我们</a></li>
                        <li><a href="#">联系我们</a></li>

                    </ul>
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="login_body l_clear">
                <div class="login_form l_float">
                    <div class="login_top">
                        <img src="{% static 'img/neau.png'%}" alt="" class="">
                        
                        <div class="login_tags b_clear">
                            <span class="top_tag l_float active" onClick="PwdLogin()">密码登录</span>
                            <span class="top_tag r_float" onClick="QrcodeLogin()">扫码登录</span>
                        </div>
                    </div>
                    <div class="login_con">
                        <form action="{% url 'app:login' %}" method="POST">
                            <div>
                                <label for="user_name">学号</label>
                                <input type="text" name="" id="user_id" placeholder="学号">
                                <img src="{% static 'img/icons/user.svg' %}">
                                <p class="tips hidden">请检查您的账号</p>
                            </div>
                            <div>
                                <label for="user_pwd">密码</label>
                                <input type="password" name="" id="user_pwd" placeholder="请输入账户密码">
                                <img src="{% static 'img/icons/lock.svg' %}">
                                <p class="tips hidden">请检查您的密码</p>
                            </div>
                            <div class="b_clear submit">
                                
                                <button type="button" id="id_login">登&nbsp;&nbsp;录</button>
                                <a href="{% url 'app:register' %}" class="r_float">点击注册你的账号!</a>
                                <p class="tips hidden">登录失败，请检查您的账户与密码</p>
                            </div>
                        </form>   
                    </div>
                    <div class="login_con hidden">
                        <div class="qr_code">
                                <img src="{% static 'img/qr.png'%}" alt="">
                                <p>请使用微信扫码登录<br>仅支持已绑定微信的账户进行快速登录</p>
                        </div>
                        
                    </div>
                    <span class="error" style="color: red"></span>
                    
                </div>
                <div class="login_ad l_float" id="AdImg">
                    <a href="">查看详情</a>
                </div>
            </div>
        </div>

        <script src="{% static 'js/login.js'%}"></script>
    </body>

    <script>
        $('#id_login').click(function () {
            $.ajax({
                url: '/login/',
                type: "POST",
                data: { user_id: $('#user_id').val(), user_pwd: $('#user_pwd').val() },
                success: function (data) {
                    if (data.status == 100) {
                        //登录成功，重定向到首页
                        location.href = 'http://www.baidu.com'
                    } else {
                        //登录失败
                        //$('.error').html(data.msg).css({'color':'red'})
                        $('.error').html(data.msg)
                    }
                },
                error: function (data) {
                    console.log(data)     //用户名密码不正确的时候打印到，前端的控制台
                }
            })
        })
    </script>

</html>

sportsequipment/templates/old/register.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>欢迎注册成为无畏的健身爱好者</title>
<!--    &lt;!&ndash;用百度的静态资源库的cdn安装bootstrap环境&ndash;&gt;-->
<!--    &lt;!&ndash; Bootstrap 核心 CSS 文件 &ndash;&gt;-->
<!--    <link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">-->
<!--    &lt;!&ndash;font-awesome 核心我CSS 文件&ndash;&gt;-->
<!--    <link href="//cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">-->
<!--    &lt;!&ndash; 在bootstrap.min.js 之前引入 &ndash;&gt;-->
<!--    <script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>-->
<!--    &lt;!&ndash; Bootstrap 核心 JavaScript 文件 &ndash;&gt;-->
<!--    <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>-->

<!--    引入自定义样式-->
    <link rel="stylesheet" href="{% static 'css/frozenui.css' %}">

<!--    <link rel="stylesheet" href="{% static 'css/base.css' %}">-->
<!--    <link rel="stylesheet" href="{% static 'AdminLTE/plugins/select2/select2.css' %}">-->
    <link rel="shortcut icon" href="{% static 'img/neau_cut.png' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>

<body background="{% static 'assets/img/background.jpg' %}" style=" background-repeat:no-repeat ;
background-size:100% 100%;
background-attachment: fixed;">
    <div class="c-login">
    <h1>注册(*为必填内容)</h1>
    {% if message %}
        <div style="color: firebrick">{{ message }}</div>
    {% endif %}
    <form class="loginForm" id="registerForm" action="{% url 'app:do_register' %}" method="post">
        {% csrf_token %}
        <input name="user_name" type="text" class="userLogo" placeholder="请您的姓名*" lay-verify="required|username"/>
        <input name="user_id" type="text" placeholder="请输入学号*" lay-verify="required"/>
        <input name="user_email" type="text" class="userLogo" placeholder="请输入邮箱*" lay-verify="email|required"/>
        <input name="password" type="password" placeholder="请输入密码*" lay-verify="required|password"/>
        <input name="repeatpwd" type="password" placeholder="请输入确认密码*" lay-verify="required|password"/>
        <input type="button" class="btn " value="注册" id="regBtn"/>
    </form>
</div>
</body>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/select2/select2.full.min.js' %}"></script>
<script>
    $('#regBtn').click(function () {
        if (!checkInputFunction($('#regBtn'))) {
            return false;
        } else {
            var form = document.getElementById("registerForm");
<!--            console.log(form);-->
            form.submit();
        }
        //下面书写验证成功后执行的内容
    });
</script>

</html>

sportsequipment/templates/old/test.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, user-scalable=no">
    <title>欢迎注册成为我们的投资者</title>
    <link rel="stylesheet" href="{% static 'css/frozenui.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'AdminLTE/plugins/select2/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link rel="shortcut icon" href="{% static 'img/buct-logo.ico' %}">


</head>
<body>

<div class="c-title">
    <div class="logo">
        <img src="{% static 'img/buct_log.png' %}" width="42" height="32" alt="北京化工大学">
    </div>
    <p class="name">股票交易管理系统</p>
</div>

<div class="c-login">
    <h1>注册(*为必填内容)</h1>
    {% if message %}
        <div style="color: firebrick">{{ message }}</div>
    {% endif %}
    <form class="loginForm" id="registerForm" action="{% url 'app:do_register' %}" method="post">
        {% csrf_token %}
        <input name="user_name" type="text" class="userLogo" placeholder="请您的姓名*" lay-verify="required|userName"/>
        <input name="phone_number" type="text" placeholder="请输入手机号码*" lay-verify="phone|required"/>
        <input name="user_sex" class="userLogo" type="text" placeholder="性别" lay-verify="required"/>
        <input name="id_no" type="text" placeholder="请输入身份证号*" lay-verify="required"/>
        <input name="user_email" type="text" class="userLogo" placeholder="请输入邮箱*" lay-verify="email"/>
        <input name="password" type="password" placeholder="请输入密码*" lay-verify="required"/>
        <input type="password" placeholder="请输入确认密码*" lay-verify="required"/>
        <input name="account_type" type="text" placeholder="请输入银行卡类型" lay-verify="required"/>
        <input name="account_number" type="text" class="codeDiv" placeholder="请输入银行卡号" lay-verify="required"/>
        <input type="button" class="btn " value="注册" id="regBtn"/>
    </form>
</div>

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/select2/select2.full.min.js' %}"></script>
<script type="text/javascript">
    /**
     * 配置验证须知
     * 1、要引入jquery.js、base.js、base.css
     * 2、提交按钮应在<form></form>内部
     * 3、在要验证的input中写上lay-verify="验证方法名|验证方法名" 可写多个但要用|分隔开
     * 4、要添加验证方法可在base.js中添加
     * 5、诺只想引用提示弹出：showTip.success("弹出提示内容");、showTip.fall("弹出提示内容")
     * 6、base.css中可以自行修改弹窗样式
     */

    $('#regBtn').click(function () {
        if (!checkInputFunction($('#regBtn'))) {
            return false;
        } else {
            var form = document.getElementById("registerForm");
            console.log(form);
            form.submit();
        }
        //下面书写验证成功后执行的内容
    });

    $('.select2').select2();
</script>

</body>
</html>