sportsequipment/app/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'app'

urlpatterns = [
    path('test' , views.common.test , name='test'),


    # 8个html页面
    path('' , views.homepage.home , name='home'), #添加映射
    path('index' , views.indexpage.index , name='index'),
    path('login', views.loginpage.login, name='login'),
    path('message', views.messagepage.message, name='message'),
    path('repair' , views.repairpage.repair , name='repair'),
    path('register', views.registerpage.register, name='register'),
    path('myrent', views.myrentpage.myrent, name='myrent'),
    path('setting', views.settingpage.setting, name='setting'),
    path('manage_borrow',views.managepage.borrow,name='manage_borrow'),
    path('manage_repair',views.managepage.repair,name='manage_repair'),





    path('do_login', views.loginpage.do_login, name='do_login'),
    path('logout', views.loginpage.logout, name='logout'),
    path('do_register', views.registerpage.do_register, name='do_register'),
    path('do_borrow', views.indexpage.do_borrow, name='do_borrow'),
    path('get_message', views.messagepage.get_message, name='get_message'),
    path('get_equipment', views.indexpage.get_equipment, name='get_equipment'),
    path('recive_equipment', views.myrentpage.recive_equipment, name='recive_equipment'),
    path('return_equipment', views.myrentpage.return_equipment, name='return_equipment'),
    path('delete_message', views.messagepage.get_message, name='delete_message'),
    path('read_message', views.messagepage.get_message, name='read_message'),
    path('submit_repair', views.repairpage.submit_repair, name='submit_repair'),

]

sportsequipment/sportsequipment/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.conf.urls import include
from django.urls import path, include, re_path
from django.views.static import serve
from sportsequipment.settings import MEDIA_ROOT

app_name = 'app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    # 处理图片显示的url,使用Django自带serve,传入参数告诉它去哪个路径找，我们有配置好的路径MEDIAROOT
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT }),
    # url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),
    # path('' , views.home , name='home'), #添加映射
]

sportsequipment/templates/boardside.html
{% load static %}
<div class="page-sidebar">
   <div class="logo" style="padding:0 0;">
      <a class="logo-img" href="{% url 'app:index' %}">
         <img class="desktop-logo" src="{%static 'assets/images/neau.png'%}" alt="">
      </a>
      <i class="ion-ios-close-empty" id="sidebar-toggle-button-close"></i>
      <h5>东北农业大学体育器材管理系统</h5>
   </div>
   <!--================================-->
   <!-- Sidebar Menu Start -->
   <!--================================-->
   <div class="page-sidebar-inner">
      <div class="page-sidebar-menu">
         <ul class="accordion-menu">
            <li class="open active" id="l1">
               <a href=""><i data-feather="home"></i>
                  <span>体育器材租借</span><i class="accordion-icon fa fa-angle-left"></i>
               </a>
               <ul class="sub-menu" style="display: block;">
                  <!-- Active Page here to design-->
                  <li class="active" id="l11"><a href="{%url 'app:index'%}">器材租借</a></li>
                  <li id="l12"><a href="{%url 'app:myrent'%}">我的租赁</a></li>
                  <li id="l13"><a href="{%url 'app:repair'%}">器材报修</a></li>
                  <li id="l14"><a href="{%url 'app:setting'%}">个人设置</a></li>
               </ul>
            </li>
            <li id="l2">
               <a href="">
                  <i data-feather="mail"></i>
                  <span>系统信息</span>
                  {% if unread_messages|length > 0 %}
                     <span class="badge badge-warning ft-right">{{unread_messages|length}}</span>
                  {% else %}
                     <i class="accordion-icon fa fa-angle-left"></i>
                  {% endif %}
               </a>
               <ul class="sub-menu" style="display: block;">
                  <li id="l21"><a href="{%url 'app:message'%}">信息中心</a></li>
               </ul>
            </li>

            {% if user.manage %}
               <li id="l3">
                  <a href="">
                     <i data-feather="database"></i>
                     <span>管理员管理</span><i class="accordion-icon fa fa-angle-left"></i>
                  </a>
                  <ul class="sub-menu" style="display: block;">
                     <!-- Active Page here to design-->
                     <li id="l31"><a href="{%url 'app:manage_borrow'%}">处理租赁订单</a></li>
                     <li id="l32"><a href="{%url 'app:manage_repair'%}">处理器材报修</a></li>
                     <li id="l33"><a href="{%url 'app:index'%}">发放奖励</a></li>
                     <li id="l34"><a href="{%url 'app:myrent'%}">添加器材</a></li>
                  </ul>
               </li>
            {% endif %}
            <!-- del left -->

            <!-- del left -->
         </ul>
      </div>
   </div>
   <!--/ Sidebar Menu End -->
   <!--================================-->
   <!-- Sidebar Footer Start -->
   <!--================================-->
   <!--/ Sidebar Footer End -->
</div>

sportsequipment/templates/commonjs.html
{% load static %}
<script src="{%static 'assets/plugins/jquery/jquery.min.js'%}"></script>
<script src="{%static 'assets/plugins/jquery-ui/jquery-ui.js'%}"></script>
<script src="{%static 'assets/plugins/popper/popper.js'%}"></script>
<script src="{%static 'assets/plugins/feather-icon/feather.min.js'%}"></script>
<script src="{%static 'assets/plugins/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{%static 'assets/plugins/pace/pace.min.js'%}"></script>
<script src="{%static 'assets/plugins/toastr/toastr.min.js'%}"></script>
<script src="{%static 'assets/plugins/countup/counterup.min.js'%}"></script>
<script src="{%static 'assets/plugins/waypoints/waypoints.min.js'%}"></script>
<script src="{%static 'assets/plugins/chartjs/chartjs.js'%}"></script>
<script src="{%static 'assets/plugins/apex-chart/apexcharts.min.js'%}"></script>
<script src="{%static 'assets/plugins/apex-chart/irregular-data-series.js'%}"></script>
<script src="{%static 'assets/plugins/simpler-sidebar/jquery.simpler-sidebar.min.js'%}"></script>
<!--<script src="{%static 'assets/js/dashboard/sales-dashboard-init.js'%}"></script>-->
<script src="{%static 'assets/js/jquery.slimscroll.min.js'%}"></script>
<script src="{%static 'assets/js/highlight.min.js'%}"></script>
<script src="{%static 'assets/js/app.js'%}"></script>
<script src="{%static 'assets/js/custom.js'%}"></script>
<script src="{%static 'assets/js/myjs.js'%}"></script>
<script src="{%static 'assets/plugins/datatables/jquery.dataTables.min.js'%}"></script>
<script src="{%static 'assets/plugins/datatables/responsive/dataTables.responsive.js'%}"></script>
<script src="{%static 'assets/plugins/datatables/extensions/dataTables.jqueryui.min.js'%}"></script>

<script>
   $("#logout").click(function (e){
           location.href = "{% url 'app:index' %}"
      });
</script>

sportsequipment/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
   <!-- The above 6 meta tags *must* come first in the head; any other head content must come *after* these tags -->
   <meta charset="utf-8">
   <meta http-equiv="x-ua-compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="keyword" content="">
   <meta name="author" content="" />
   <!-- Page Title here to disign -->
   <title>首页</title>
   {%include 'head.html'%}
</head>


<body>
   <!--================================-->
   <!-- Page Container Start -->
   <!--================================-->
   <div class="page-container">
      <!--================================-->
      <!-- Page Sidebar Start -->
      <!--================================-->
      {%include 'boardside.html'%}
      <!--/ Page Sidebar End -->
      <!--================================-->
      <!-- Page Content Start -->
      <!--================================-->
      <div class="page-content">
         <!--================================-->
         <!-- Page Header Start -->
         <!--================================-->
         {%include 'top.html'%}
         <!--/ Page Header End -->
         <!--================================-->
         <!-- Page Inner Start -->
         <!--================================-->
         <div class="page-inner">
            <!-- Main Wrapper -->
            <div id="main-wrapper">
               <!--================================-->
               <!-- Breadcrumb Start -->
               <!--================================-->
               <!-- here to design -->
               <div class="row row-xs">
                     {% for i in equipments %}
                        <div class="col-sm-6 col-xl-3">
                           <div class="card mg-b-20">
                              <div class="card-body text-center">
                                 <a href="{%url 'app:get_equipment'%}?eid={{i.eid}}">
                                    <img src="{{ MEDIA_URL }}{{i.img_url}}" alt="" class="img-fluid wd-100p ht-250">
                                 </a>
                                 <h5 class="tx-dark tx-13 tx-medium mg-y-15 d-block">{{i.brand}}{{i.ename}}</h5>
                                 <p>
                                    {{i.introduce}}
                                 </p>
                                 <strong class="text-center mt-3">已经被借出{{i.count}}次</strong>
                                 <a href="{%url 'app:do_borrow'%}?eid={{i.eid}}&consume=7" class="btn btn-sm btn-label-success">立即借用</a>
                              </div>
                           </div>
                        </div>
                     {% endfor %}
                  </div>
               <!--/ Breadcrumb End -->
               <!--================================-->
            </div>
            <!--/ Main Wrapper End -->
         </div>
         <!-- Label Alignment Form Start -->
         <!--================================-->
         <!--/ Label Alignment Form End -->
         <!--================================-->

         <!--================================-->
         <!--/ Page Inner End -->
         <!--================================-->
         <!--================================-->
         <!-- Page Footer Start -->
         <!--================================-->
         {%include 'footer.html'%}
         <!--/ Page Footer End -->
      </div>
      <!--/ Page Content End -->
   </div>
   <!--/ Page Container End -->
   <!--================================-->

   <!--================================-->
   <!-- Footer Script -->
   <!--================================-->
   {%include 'commonjs.html'%}
</body>

</html>

sportsequipment/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">
   <head>
      <!-- The above 6 meta tags *must* come first in the head; any other head content must come *after* these tags -->
      <meta charset="utf-8">
	   <meta http-equiv="x-ua-compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
	   <meta name="description" content="">
	   <meta name="keyword" content="">
	   <meta name="author"  content=""/>
      <!-- Page Title -->
      <title>登录</title>
     {%include 'head.html'%}
   </head>
   <body background="{% static 'assets/images/background.jpg' %}" style=" background-repeat:no-repeat ;
background-size:100% 100%;
background-attachment: fixed;">
      <!--================================-->
      <!-- User Singin Start -->
      <!--================================-->			
      <div class="ht-100v d-flex">
         <div class="card shadow-none pd-20 mx-auto wd-300 text-center bd-1 align-self-center">
            <h4 class="card-title mt-3 text-center">login in</h4>
            <p class="text-center">登入账户</p>
            <form action = "{% url 'app:do_login' %}" method = "post">
               <div class="form-group input-group">
                  <div class="input-group-prepend">
                     <span class="input-group-text pd-x-9"> <i class="fa fa-envelope"></i> </span>
                  </div>
                  <input class="form-control form-control-sm" placeholder="请输入邮箱号" id="form-email" type="text" name = "email" required>
               </div>
               <div class="form-group input-group">
                  <div class="input-group-prepend">
                     <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                  </div>
                  <input class="form-control form-control-sm" placeholder="请输入密码" id="form-password" type="password" name = "password" required>
               </div>
               <div class="form-group">
                  <input type="submit"  class="btn btn-custom-primary btn-block tx-13 hover-white" id="submit_button" name = "登录" value = "登录">
               </div>
               <p class="text-center">没有账户?<br/> <a href="{% url 'app:register' %}">注册账户</a> </p>
            </form>
            {% if message %}
               <div class="alert alert-primary" role="alert" id="message">
                  {{message}}
               </div>
            {%endif%}
         </div>
      </div>
      <!--/ User Singin End -->
      <!--================================-->
      <!-- Footer Script -->
      <!--================================-->	
      <script src="{%static 'assets/plugins/jquery/jquery.min.js'%}"></script>
      <script src="{%static 'assets/plugins/jquery-ui/jquery-ui.js'%}"></script>
      <script src="{%static 'assets/plugins/popper/popper.js'%}"></script>
      <script src="{%static 'assets/plugins/bootstrap/js/bootstrap.min.js'%}"></script>
      <script src="{%static 'assets/plugins/pace/pace.min.js'%}"></script>
      <script src="{%static 'assets/js/jquery.slimscroll.min.js'%}"></script>
      <script src="{%static 'assets/js/custom.js'%}"></script>

      <script>
      function IsEmail(str) {
            var reg = /^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$/;
            return  reg.test(str);
      }
      $("#submit_button").click(function (e) {
            var form_email = $('#form-email');
            var form_password = $('#form-password');
            let email = form_email.val();
            let password = form_password.val();
            if (IsEmail(email)){
               var option = {
                   url: "{% url 'app:do_login' %}",
                   data: {
                    "email": email,
                    "password": password,
                   },
                   type: 'POST',
                   dataType: 'json',
               };
               console.log(option);
               $.ajax(option);
            }
            else{
               alert("请检查邮箱格式");
               return false;
            }
            return true;
      });
      </script>
   </body>
</html>

sportsequipment/templates/message.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
   <!-- The above 6 meta tags *must* come first in the head; any other head content must come *after* these tags -->
   <meta charset="utf-8">
   <meta http-equiv="x-ua-compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="keyword" content="">
   <meta name="author" content="" />
   <!-- Page Title here to disign -->
   <title>消息中心</title>
   {%include 'head.html'%}
</head>


<body>
   <!--================================-->
   <!-- Page Container Start -->
   <!--================================-->
   <div class="page-container">
      <!--================================-->
      <!-- Page Sidebar Start -->
      <!--================================-->
      {%include 'boardside.html'%}
      <!--/ Page Sidebar End -->
      <!--================================-->
      <!-- Page Content Start -->
      <!--================================-->
      <div class="page-content">
         <!--================================-->
         <!-- Page Header Start -->
         <!--================================-->
         {%include 'top.html'%}

         <div class="page-inner pd-0-force mg-0-force ht-100vh bg-white">
               <div class="row no-gutters wd-100p clearfix">
				  <!--================================-->
				  <!-- Start Left sidebar -->
				  <!--================================-->
                  <div class="col-md-8 col-lg-9 email-right-sidebar">
                     <div class="card bd-l-0-force bd-t-0-force bd-b-0-force">

                        <div class="card-body">
                           <div class="btn-toolbar" role="toolbar">
                              <div class="btn-group">
                                 <button type="button" class="btn btn-light">
                                    <strong><a href="{%url 'app:delete_message'%}?mid={{mail.eid}}">删除</a></strong>
                                 </button>
                                 <button type="button" class="btn btn-light">
                                    <strong><a href="{%url 'app:read_message'%}?mid={{mail.eid}}">标记为已读</a></strong>
                                 </button>
                              </div>
                           </div>

                           <div class="table-responsive mg-t-20 mg-b-15">
                              {%for message in messages%}
                                 <table class="table table-hover mb-0">
                                    <tbody>
                                       <tr class="active">
                                          <td class="wd-5p">
                                             <div class="d-flex custom-control custom-checkbox">
                                                <input type="checkbox" class="custom-control-input" id="customCheck1">
                                                <label class="custom-control-label" for="customCheck1"></label>
                                             </div>
                                          </td>
                                          <td class="wd-15p">admin</td>
                                          <td class="wd-55p">
                                             <span class="badge badge-outlined badge-danger mr-2">系统</span>
                                             <a href="{% url 'app:get_message' %}?mid={{message.mid}}">{{message.part}}...</a>
                                          </td>
                                          <td class="wd-25p">
                                             <p class="mb-0 tx-10 tx-gray-500">01-02-2019, 11:46AM</p>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                              {%endfor%}
                           </div>


                        </div>
                     </div>
                  </div>
                  <!--/ End email-rightbar -->
               </div>
            </div>

         {%include 'footer.html'%}
         <!--/ Page Footer End -->
      </div>
      <!--/ Page Content End -->
   </div>
   <!--/ Page Container End -->
   <!--================================-->

   <!--================================-->
   <!-- Footer Script -->
   <!--================================-->
   {%include 'commonjs.html'%}
   <script>
      var l1 = document.getElementById('l11');
      var l2 = document.getElementById('l21');
      var L1 = document.getElementById('l1');
      var L2 = document.getElementById('l2');
      l1.classList.remove("active");
      L1.classList.remove("open","active");
      l2.classList.add("active");
      L2.classList.add("open","active");
   </script>
</body>

</html>

sportsequipment/templates/messagedetail.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
   <!-- The above 6 meta tags *must* come first in the head; any other head content must come *after* these tags -->
   <meta charset="utf-8">
   <meta http-equiv="x-ua-compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="keyword" content="">
   <meta name="author" content="" />
   <!-- Page Title here to disign -->
   <title>消息详情</title>
   {%include 'head.html'%}
</head>


<body>
   <!--================================-->
   <!-- Page Container Start -->
   <!--================================-->
   <div class="page-container">
      <!--================================-->
      <!-- Page Sidebar Start -->
      <!--================================-->
      {%include 'boardside.html'%}
      <!--/ Page Sidebar End -->
      <!--================================-->
      <!-- Page Content Start -->
      <!--================================-->
      <div class="page-content">
         <!--================================-->
         <!-- Page Header Start -->
         <!--================================-->
         {%include 'top.html'%}

         <div class="page-inner pd-0-force mg-0-force ht-100vh bg-white">
               <div class="row no-gutters wd-100p clearfix">
				  <!--================================-->
				  <!-- Start Left sidebar -->
				  <!--================================-->
                  <div class="col-md-8 col-lg-9 email-right-sidebar">
                     <div class="card bd-l-0-force bd-t-0-force bd-b-0-force">

                        <div class="card-body">

                           <div class="btn-toolbar" role="toolbar">
                              <div class="btn-group">
                                 <button type="button" class="btn btn-light">
                                    <strong><a href="{%url 'app:delete_message'%}?mid={{mail.eid}}">删除</a></strong>
                                 </button>
                                 <button type="button" class="btn btn-light">
                                    <strong><a href="{%url 'app:read_message'%}?mid={{mail.eid}}">标记为已读</a></strong>
                                 </button>
                                 <button type="button" class="btn btn-light">
                                    <strong><a href="{%url 'app:message'%}">返回</a></strong>
                                 </button>
                              </div>
                           </div>

                           <div class="pd-y-15 mg-t-15 bd-b">

                              <div class="row">
                                 <div class="col-md-6 toolbar-left">
                                    <!--Sender Information-->
                                    <div class="d-flex">
                                       <span class="mg-r-10">
                                       <img src="http://via.placeholder.com/150" class="img-fluid wd-40 rounded-circle" alt="">
                                       </span>
                                       <div class="text-left">
                                          <div class="tx-bold">Lisa D. Smith</div>
                                          <span >example@mail.com</span>
                                       </div>
                                    </div>
                                 </div>


                                 <div class="col-md-6 text-md-right hidden-xs">
                                    <!--Details Information-->
                                    <p class="mg-0"><small >{{message.send_time}}</small></p>
                                 </div>
                              </div>
                           </div>
                           <div class="row mg-t-20 mg-b-15">
                              <div class="col-md-12">
                                 <div class="mg-b-20 bd-b">
                                     <p>
                                        <strong>
                                           {{message.content}}
                                        </strong>
                                     </p>
                                 </div>
                              </div>
                           </div>
                     </div>
                  </div>
                  <!--/ End email-rightbar -->
               </div>
            </div>
         </div>
         {%include 'footer.html'%}
         <!--/ Page Footer End -->
      </div>
      <!--/ Page Content End -->
   </div>
   <!--/ Page Container End -->
   <!--================================-->

   <!--================================-->
   <!-- Footer Script -->
   <!--================================-->
   {%include 'commonjs.html'%}
   <script>
      var li1 = document.getElementById('1');
      var li3 = document.getElementById('3');
      li1.classlist.remove("active");
      li3.classlist.add("active");
   </script>
</body>

</html>

sportsequipment/templates/myrent.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
   <!-- The above 6 meta tags *must* come first in the head; any other head content must come *after* these tags -->
   <meta charset="utf-8">
   <meta http-equiv="x-ua-compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="keyword" content="">
   <meta name="author" content="" />
   <!-- Page Title here to disign -->
   <title>我的租借</title>
   {%include 'head.html'%}
</head>


<body>
   <!--================================-->
   <!-- Page Container Start -->
   <!--================================-->
   <div class="page-container">
      <!--================================-->
      <!-- Page Sidebar Start -->
      <!--================================-->
      {%include 'boardside.html'%}
      <!--/ Page Sidebar End -->
      <!--================================-->
      <!-- Page Content Start -->
      <!--================================-->
      <div class="page-content">
         <!--================================-->
         <!-- Page Header Start -->
         <!--================================-->
         {%include 'top.html'%}
         <!--/ Page Header End -->
         <!--================================-->
         <!-- Page Inner Start -->
         <!--================================-->
         <div class="page-inner">
            <!-- Main Wrapper -->
            <div id="main-wrapper">
               <!--================================-->
               <!-- Breadcrumb Start -->
               <!--================================-->
               <!-- here to design -->
               <div class="pageheader pd-t-25 pd-b-35">
                  <div class="pd-t-5 pd-b-5">
<!--                     <h1 class="pd-0 mg-0 tx-20">东北农业大学体育器材管理系统概述</h1>-->
                  </div>
               </div>
               <!--/ Breadcrumb End -->
               <!--================================-->
            </div>
            <!--/ Main Wrapper End -->
         </div>
         <!-- Label Alignment Form Start -->
         <!--================================-->
         <div class="col-md-12 col-lg-12">
            <div class="card mg-b-20">
               <div class="card-header">
                  <h4 class="card-header-title">
                     <span class="tx-14 tx-md-24 tx-dark">我的租借订单</span>
                  </h4>
               </div>


               <table class="mt">
                  <thead>
                     <tr>
                        <td>订单编号</td>
                        <td>器材名称</td>
                        <td>管理员id</td>
                        <td>借用时间</td>
                        <td>应还时间</td>
                        <td>当前状态</td>
                     </tr>
                  </thead>
                  <tbody>
                  {%for i in orders%}
                     <tr>
                        <td>{{i.oid}}</td>
                        <td><a href="{%url 'app:index'%}">{{i.equipment.brand}}{{i.equipment.ename}}</a></td>
                        <td>{{i.equipment.controller.uid}}</td>
                        <td>{{i.rent_time}}</td>
                        <td>{{i.return_time}}</td>
                        {% if i.status == "已完成"%}
                           <td style="color:green">已结束</td>
                        {%elif i.status == "已归还"%}
                           <td style="color:black"><a href="{%url 'app:index'%}">已归还</a></td>
                        {%elif i.status == "待领取"%}
                           <td style="color:orange">待领取(<a href="{%url 'app:recive_equipment'%}?oid={{i.oid}}">去领取</a>)</td>
                        {%else%}
                           <td style="color:red">未归还(<a href="{%url 'app:return_equipment'%}?oid={{i.oid}}">去归还</a>)</td>
                        {%endif%}
                     </tr>
                  {%endfor%}
                  </tbody>
               </table>
            </div>
         </div>
         <!--/ Label Alignment Form End -->
         <!--================================-->

         <!--================================-->
         <!--/ Page Inner End -->
         <!--================================-->
         <!--================================-->
         <!-- Page Footer Start -->
         <!--================================-->
         {%include 'footer.html'%}
         <!--/ Page Footer End -->
      </div>
      <!--/ Page Content End -->
   </div>
   <!--/ Page Container End -->
   <!--================================-->

   <!--================================-->
   <!-- Footer Script -->
   <!--================================-->
   {%include 'commonjs.html'%}
   <script>
      var l1 = document.getElementById('l11');
      var l2 = document.getElementById('l12');
      l1.classList.remove("active");
      l2.classList.add("active");
   </script>
</body>

</html>